import { Inter } from 'next/font/google'
import Navigation from './components/navigation'
import Footer from './components/footer'
import Landing from './components/landing'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chri-post',
  description: 'Generated by henry',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Landing />
        {children}
        
        <Footer />
      </body>
    </html>
  )
}
